# our base image
FROM postgres:14.1-alpine

# set up the postgre sql environment
ENV POSTGRES_DB=db \
   POSTGRES_USER=usr \
   POSTGRES_PASSWORD=pwd

# copy the init script
COPY CreateScheme.sql /docker-entrypoint-initdb.d
COPY InsertData.sql /docker-entrypoint-initdb.d

# set the hostname
# ENV PGHOST=postgres


